### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by RajChanchal** [gchilds/MTAudioProcessingTap-in-Swift#2] opened 2017-05-22 10:50 UTC
App crashes on following line:
`let audioTrack = playerItem.asset.tracks(withMediaType: AVMediaTypeAudio).first!`
The tracks array property returns an empty array.

**Comment by gchilds** [comment] 2018-10-31 19:59
If you're talking about a remote asset, then some remote assets (e.g. HLS) don't work with audio taps after a certain iOS version, so this would be a duplicate of issue #3.

**Closed as completed by gchilds** 2018-10-31 19:59 UTC
